name: Java CI with Maven

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
   

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
          distribution: 'adopt'
          java-version: '17'

    - uses: actions/setup-node@v2
      with:
       node-version: '12'
    - run: |
            npm install -g appium@v1.20.2
            appium -v
            appium &>/dev/null &

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: mvn clean test -Pandroid
